-- Savings App Pro - Database Schema
-- Project: Database Design for Savings Management
-- Version: 1.3

-- 1. Creamos la tabla de Frecuencias
create table public.frequencies (
  frequency_id smallint generated by default as identity primary key,
  frequency_name text not null unique
);

-- 2. Creamos la tabla de Metas de Ahorro
create table public.savings_goals (
  goal_id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  frequency_id smallint references public.frequencies(frequency_id) not null,
  goal_name text not null,
  target_amount numeric(12, 2) not null,
  periodic_amount numeric(12, 2) not null,
  start_date date not null,
  end_date date not null,
  is_system_goal boolean default false
);

-- 3. Creamos el ENUM para blindar los tipos de transacción
create type transaction_type_enum as enum ('deposito', 'retiro');

-- 4. Creamos la tabla de Transacciones
create table public.goal_transactions (
  transaction_id bigint generated by default as identity primary key,
  goal_id bigint references public.savings_goals(goal_id) on delete cascade not null,
  amount numeric(12, 2) not null,
  transaction_type transaction_type_enum not null,
  transaction_date timestamp with time zone default timezone('utc'::text, now()) not null
);
